# Generated by Django 4.0.1 on 2022-02-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_magasin_alter_person_sex_profilemagasin_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='magasin',
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ'), ('NON-DEFINI', 'NON-DEFINI')], max_length=10),
        ),
    ]
