# Generated by Django 4.0.1 on 2022-02-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_produit_magasin_alter_person_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
