# Generated by Django 4.0.1 on 2022-02-07 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('BJ', 'BENIN'), ('BF', 'BURKINA-FASO'), ('CI', "COTE D'IVOIRE"), ('SN', 'SENEGAL')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='PRODUCT_IMG')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_magasin', to='polls.magasin')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
